name: Nightly Run

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        scala: [2.13]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: master

      - name: Setup Java (zulu@8)
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 8
          cache: sbt

      - name: Build project
        run: sbt -J-Xmx2G '++ ${{ matrix.scala }}' test
